### ISSUE TITLE
Expose this module as a ruby gem

### ISSUE THREAD

**Issue by flbulgarelli** [gobstones/gs-board#11]
It would be nice that this module could also be exposed as a ruby gem, thus making integration with mumuki smooth. 

Here there are some - in progress - samples of how to wrap a repository in an unobtrusive way: 

 * https://github.com/mumuki/mulang/pull/146
 * https://github.com/mumuki/mumuki-styles/pull/24

**Comment by afska** [comment]
Done! Now it's integrated with Travis.
