### ISSUE TITLE
Page loading times are too high

### ISSUE THREAD

**Issue by julian-berbel** [gobstones/gs-board#14]
Hi there :wave: 

I was tracking an issue with loading times in mumuki and I ended up here.

![image](https://user-images.githubusercontent.com/11720274/37929080-51ae5ff2-3115-11e8-88d1-3c4602bd8ab8.png)
While 2 seconds is somewhat tolerable, the processing time goes up tenfold in the tablet we got for testing purposes.

After struggling for a while, I was able to isolate the problem to this commit: aee6c02ae59323cd44b9a0e9c9dc891dc9b5815d

After that I found the shown regex and use in one of gs-board's dependencies (shadycss)
`varApply: /[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,`

```
function removeCustomPropApply(cssText) {
  debugger;
  return cssText
    .replace(RX.mixinApply, '')
    .replace(RX.varApply, '');
}
```

From what I gather, this regex is being called on the whole css, so having an image embedded in it is making its evaluation take really long.

It would be great if you could unembed the image base64 and instead reference it with a url since this should speed the loading process greatly.
https://github.com/gobstones/gs-board/blob/8e4e94485e7380753f8fba3ba65b0a2610736540/src/components/gs-board/style.scss#L98-L100

**Comment by afska** [comment]
Hey,

I've just fixed this at https://github.com/gobstones/gs-board/commit/768c44e93d3d7da5b6e17b13596216693846cb67, it's published as version `1.14`.
