### ISSUE TITLE
Los assets de las vestimentas no están perfectamente alineados

### ISSUE THREAD

**Issue by flbulgarelli** [gobstones/gs-board#17]
Miren esta captura de pantalla: 

![board1](https://user-images.githubusercontent.com/677436/39197246-684ea09e-47ba-11e8-913c-92e23f74e77b.png)

Si se fijan, las celdas no están perfectamente alineadas, pese a que el asset es cuadrado: 

![tierra_seca4-01](https://user-images.githubusercontent.com/677436/39197564-2d4b04e6-47bb-11e8-82f2-814a62dafdf6.png)

**Comment by afska** [comment]
Parece un glitchcito del escalado de Chrome, cuando se usa `transform: scale(1.23)` (o cualquier número que lo obligue a redondear pixeles).

sin escalar:
![screenshot17](https://user-images.githubusercontent.com/1631752/39286649-83a0d1dc-48f5-11e8-9179-9c8e08bcd786.png)

escalando:
![screenshot18](https://user-images.githubusercontent.com/1631752/39286650-8b6f0a00-48f5-11e8-8188-35b0b434354d.png)

Con valores de escala como 1.12, 1.2, 1.32, 1.4, 1.52, 1.6, ... se comporta bien.

___

En Firefox Quantum se ve bien siempre:

sin escalar:
![screenshot20](https://user-images.githubusercontent.com/1631752/39286665-9f6bd43e-48f5-11e8-848d-9d2012adb334.png)

escalando:
![screenshot21](https://user-images.githubusercontent.com/1631752/39286670-a6c64bba-48f5-11e8-941e-f13b5eb01013.png)

___

En fin, es un issue de quien usa el tablero y no del componente tablero en sí.

[Lo acabo de arreglar en gobstones-web](https://github.com/gobstones/gobstones-web/commit/da881184e4845efbd0baf08ed3e587fd1e69f6be) a costa de tener un redimensionado [menos fluído](https://www.youtube.com/watch?v=ZdatUHF_C9U). Quedó subido a [staging](https://gobstones.github.io/gobstones-web-staging).

**Comment by afska** [comment]
@fidel-ml FYI
